ref_genome: static/hg19.fa
ref_genome_masked: static/hg19.fa
bam_ref: static/FAF04090.bam
FAST5_basedir: /home/sander/nanopore/Guppy_testing
trainingset_dir: static/Trainingsets
chr_sizes: static/hg19.chrom.sizes
email: "info@mail.com"
max_CpG: 100000
perform_basecalling: yes
guppy_basecall_server_path: "/usr/bin/guppy_basecall_server"