T20.061ref_genome: /home/vml/MagDx/static/hg19.fa
ref_genome_masked: /home/vml/MagDx/static/hg19.fa
bam_ref: /home/vml/MagDx/static/FAF04090.bam
FAST5_basedir: /home/vml/Guppy_testing
trainingset_dir: /home/vml/MagDx/static/Trainingsets
chr_sizes: /home/vml/MagDx/static/hg19.chrom.sizes
email: "info@mail.com"
max_CpG: 100000
perform_basecalling: yes